### ISSUE TITLE
Practica Test Case

### ISSUE THREAD

**Issue by CarlosSD16** [SistemasTecTlaxiaco/practica-de-test-case-entrevista-tr#2]
[Practica de Test Cases.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-test-case-entrevista-tr/files/7346609/Practica.de.Test.Cases.pdf)

**Comment by ThorSampy** [comment]
Cuenta con los puntos establecidos en la rubrica: 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
